server.error.include-message=always
server.error.include-stacktrace=always

astra.token=${ASTRA_TOKEN}
astra.database-id=${ASTRA_DATABASE_ID}
astra.database-region=${ASTRA_DATABASE_REGION:us-east-2}
astra.keyspace=${ASTRA_KEYSPACE:default_keyspace}
astra.table=${ASTRA_TABLE:pdfchat}

groq.api-key=${GROQ_API_KEY}
groq.base-url=${GROQ_BASE_URL:https://api.groq.com/openai/v1/}
groq.model=${GROQ_MODEL:llama-3.3-70b-versatile}
